// flow-typed signature: f52300cc5744dde5cc15bc57edc39b18
// flow-typed version: <<STUB>>/decko_v^1.2.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'decko'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'decko' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'decko/dist/decko' {
  declare module.exports: any;
}

declare module 'decko/src/decko' {
  declare module.exports: any;
}

// Filename aliases
declare module 'decko/dist/decko.js' {
  declare module.exports: $Exports<'decko/dist/decko'>;
}
declare module 'decko/src/decko.js' {
  declare module.exports: $Exports<'decko/src/decko'>;
}
